In [209]:
from matplotlib import pyplot as plt 
import numpy as np 
import pandas as pd 
import plotly.express as px
import plotly.io as pio
import plotly.graph_objs as go
import plotly.offline as pyo
import pickle

from collections import Counter

import plotly.graph_objects as go
import plotly.express as px

from matplotlib import rc

### Load pickle

In [602]:
read_input = open('data/ADC_FTLD_subtypes_agecorrected_zscore_final.pickle','rb')
load_inputs = pickle.load(read_input)
read_input.close()

T, S, X = load_inputs

- T --> timeline (timeline object)

- S --> subjects (dict)

Install snowphlake package from github

In [603]:
# !pip install git+https://github.com/snowphlake-dpm/snowphlake

In [604]:
S.keys()

dict_keys(['staging', 'subtypes', 'subtypes_weights', 'atypicality', 'atypicality_all'])

In [605]:
len(S['staging'])

1080

### Create diagnosis variable

- FTD = Frontotemporal Dementia

In [606]:
subtypes = S['subtypes']

In [607]:
np.isnan(S['subtypes'][900])

True

In [608]:
# For more bars, experimentation

subtypes = S['subtypes']
np.isnan(S['subtypes'][900])

# diagnosis = ['Control' if np.isnan(subtype) else "FTD" for subtype in subtypes]

subtypes = ['Control' if np.isnan(subtype) else subtype for subtype in subtypes]

# subtypes

mapping = {np.float64(0.): 'Subtype 0', 1.: 'Subtype 1', 2.: 'Subtype 2', 3.: 'Subtype 3', 4.: 'Subtype 4','Control':'Control'}

# mapping

diagnosis = [mapping[subtype] for subtype in subtypes]
# diagnosis

### Check for diagnosis count

In [609]:
counter = dict(Counter(diagnosis))
counter

{'Subtype 0': 90,
 'Subtype 4': 142,
 'Subtype 1': 67,
 'Subtype 3': 62,
 'Subtype 2': 38,
 'Control': 681}

In [610]:
check = ['Control' if np.isnan(stage) else "FTD" for stage in staging]

counter = dict(Counter(check))
counter

{'FTD': 1080}

### Convert Nans to 0.0

In [611]:
staging = list(S['staging'])
staging = [np.float64(0.0) if np.isnan(stage) else stage for stage in staging]

dic = {'Diagnosis': diagnosis, 'Staging': staging}
dic

data = pd.DataFrame(dic)
data

Diagnosis   Staging
0     Subtype 0  0.644969
1     Subtype 0  0.659062
2     Subtype 0  0.631944
3     Subtype 0  0.863420
4     Subtype 4  0.643785
...         ...       ...
1075    Control  0.000000
1076    Control  0.000000
1077    Control  0.000000
1078    Control  0.000000
1079    Control  0.000000

[1080 rows x 2 columns]

In [612]:
labels = list(set(diagnosis))
# labels = labels[::-1]

# labels = ['Subtype 0', 'Subtype 1', 'Subtype 2', 'Subtype 3','Subtype 4', 'Control']
# labels

In [613]:
x = np.arange(0,1.1,0.1)
x

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

#### Get indexes

In [614]:
# diagnosis = np.array(['Control' if np.isnan(subtype) else "FTD" for subtype in subtypes])

diagnosis = np.array(diagnosis)
staging = np.array([np.float64(0.0) if np.isnan(stage) else stage for stage in staging])

idx_Control = np.where(diagnosis=='Control')
idx_Control = idx_Control[0]

idx_FTD = np.where(diagnosis=='FTD')
idx_FTD = idx_FTD[0]
len(idx_FTD)

# =====================
idx_0 = np.where(diagnosis=='Subtype 0')
idx_0 = idx_0[0]

idx_1 = np.where(diagnosis=='Subtype 1')
idx_1 = idx_1[0]

idx_2 = np.where(diagnosis=='Subtype 2')
idx_2 = idx_2[0]

idx_3 = np.where(diagnosis=='Subtype 3')
idx_3 = idx_3[0]

idx_4 = np.where(diagnosis=='Subtype 4')
idx_4 = idx_4[0]
len(idx_4)

142

In [615]:
idx_list = []
for l in labels:
    idx = np.where(diagnosis==l)
    idx = idx[0]
    idx_list.append(idx)


In [616]:
labels

['Subtype 2', 'Subtype 1', 'Subtype 0', 'Subtype 3', 'Subtype 4', 'Control']

In [637]:
freq,binc=np.histogram(staging[idx_Control],bins=10)
freq = (1.*freq)/len(staging)
freq

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.63055556, 0.        , 0.        , 0.        , 0.        ])

#### Get grequency and set number of bins

In [617]:
# JUST FOR TESTING
count=-1
num_bins = 10
freq_all = []

width = np.repeat(0.02, num_bins)
width

array([0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02])

In [618]:
# 5 SUBTYPES

subtypes = ['Control' if np.isnan(subtype) else subtype for subtype in S['subtypes']]

mapping = {np.float64(0.): 'Subtype 0', 1.: 'Subtype 1', 2.: 'Subtype 2', 3.: 'Subtype 3', 4.: 'Subtype 4','Control':'Control'}

diagnosis = [mapping[subtype] for subtype in subtypes]

diagnosis = np.array(diagnosis)
staging = np.array([np.float64(0.0) if np.isnan(stage) else stage for stage in S['staging']])

# labels = list(set(diagnosis))
# labels = labels[::-1]

idx_Control = np.where(diagnosis=='Control')
idx_Control = idx_Control[0]


# =====================
idx_0 = np.where(diagnosis=='Subtype 0')
idx_0 = idx_0[0]

idx_1 = np.where(diagnosis=='Subtype 1')
idx_1 = idx_1[0]

idx_2 = np.where(diagnosis=='Subtype 2')
idx_2 = idx_2[0]

idx_3 = np.where(diagnosis=='Subtype 3')
idx_3 = idx_3[0]

idx_4 = np.where(diagnosis=='Subtype 4')
idx_4 = idx_4[0]

labels = list(mapping.values())
labels

['Subtype 0', 'Subtype 1', 'Subtype 2', 'Subtype 3', 'Subtype 4', 'Control']

In [642]:
# Controls & FTD

diagnosis = np.array(['Control' if np.isnan(subtype) else "FTD" for subtype in S['subtypes']])
staging = np.array([np.float64(0.0) if np.isnan(stage) else stage for stage in S['staging']])

labels = list(set(diagnosis))

idx_Control = np.where(diagnosis=='Control')
idx_Control = idx_Control[0]

idx_FTD = np.where(diagnosis=='FTD')
idx_FTD = idx_FTD[0]

labels

['FTD', 'Control']

In [652]:
count=-1
# fig, ax = plt.subplots(figsize=(12, 6))
# plt.style.use('seaborn-whitegrid')
rc('font',**{'family':'sans-serif','sans-serif':['Helvetica']})
rc('mathtext', fontset='stixsans');
c = ['#4daf4a','#377eb8','#e41a1c', '#ffff00']

counter = dict(Counter(diagnosis))

fig = go.Figure()


# for idx in [idx_0,idx_1,idx_2,idx_3,idx_4,idx_Control]:
for idx in [idx_FTD, idx_Control]:
    
            if len(idx)>0:
                count=count+1;
            freq,binc=np.histogram(staging[idx],bins=num_bins)
            freq = (1.*freq)/len(staging)
            if count>0:
                freq=freq+freq_all[count-1]
            freq_all.append(freq)
            bw=1/(2.*num_bins)
#             ax.bar(binc[:-1],freq,width=bw,color=c[count],label=labels[count],zorder=3-count)
            
# plt.show()
            
#             label = labels[count]
    
            fig.add_trace(go.Bar(
                        x=binc[:-1],
                        y=freq,
                        name=f'{labels[count]} (n = {counter[labels[count]]})',
                        width=width))
            
fig.update_layout(
    title="Patient Staging",
    xaxis_title="Disease Stage",
    yaxis_title="Frequency of occurences",
    xaxis = dict(
        tickmode = 'linear',
        tick0 = 0.0,
        dtick = 0.1
    ),
    barmode='relative',
    legend_font_size=16,
    legend=dict(
        yanchor="top",
        y=0.95,
        xanchor="right",
        x=0.95),
    autosize = False,
    width=1000,
    height=800
)



fig.update_xaxes(range=[-0.05, 1.0])
            
fig.show()


In [629]:
count

0

In [596]:
idx_list = []
for l in labels:
        idx = np.where(diagnosis==l)
        idx = idx[0]
        idx_list.append(idx)
    
len(idx_list[0])

399

## Patient staging function

In [577]:
def patient_staging(S, diagnosis, num_bins):
    """
    Creates a barplot
    :param S: dictionary, Snowphlake output
    :param diagnosis: np.array or list; with diagnosis labels corresponding to records in S
    :return: dictionary with scores for each DK region for chosen subtype
    """
    
    subtypes = list(S['subtypes'])
    subtypes = ['Control' if np.isnan(subtype) else subtype for subtype in subtypes]


    staging = list(S['staging'])
    staging = [np.float64(0.0) if np.isnan(stage) else stage for stage in staging]
    staging = np.array([np.float64(0.0) if np.isnan(stage) else stage for stage in staging])

    
    labels = list(set(diagnosis))
    diagnosis = np.array(diagnosis)
    
    c = ['#4daf4a','#377eb8','#e41a1c', '#ffff00']
    
    idx_list = []
    for l in labels:
        idx = np.where(diagnosis==l)
        idx = idx[0]
        idx_list.append(idx)
        
    count=-1
    num_bins = num_bins
    freq_all = []
    width = np.repeat(0.02, num_bins)
    counter = dict(Counter(diagnosis))

    fig = go.Figure()


    
    for idx in idx_list:
                if len(idx)>0:
                    count=count+1;
                freq,binc=np.histogram(staging[idx],bins=num_bins)
                freq = (1.*freq)/len(staging)
                if count>0:
                    freq=freq+freq_all[count-1]
                freq_all.append(freq)
                bw=1/(2.*num_bins)

                label = labels[count]

                fig.add_trace(go.Bar(
                            x=binc[:-1],
                            y=freq,
                            name=f'{labels[count]} (n = {counter[labels[count]]})',
                            width=width))

    fig.update_layout(
        title="Patient Staging",
        xaxis_title="Disease Stage",
        yaxis_title="Frequency of occurences",
        xaxis = dict(
            tickmode = 'linear',
            tick0 = 0.0,
            dtick = 0.1
        ),
        barmode='group',
        legend_font_size=16,
        legend=dict(
            yanchor="top",
            y=0.95,
            xanchor="right",
            x=0.95),
        autosize = False,
        width=1000,
        height=800
    )



    fig.update_xaxes(range=[-0.05, 1.0])

    fig.show()






In [578]:
# FOR TESTING

# many subtypes
mapping = {np.float64(0.): 'Subtype 0', 1.: 'Subtype 1', 2.: 'Subtype 2', 3.: 'Subtype 3', 4.: 'Subtype 4','Control':'Control'}
diagnosis = [mapping[subtype] for subtype in subtypes]


In [581]:
# Controls & FTD
diagnosis = ['Control' if np.isnan(subtype) else "FTD" for subtype in S['subtypes']]

In [582]:
patient_staging(S, diagnosis, 10)

In [510]:
# S['subtypes'][399:]